# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98b730ebf9d57b144ff54e73440aa3f61829b221ca75ff7da541d3e5ccee2bf9258ec73c065dab95812125362abf24a97d7856abaaa8c226e31cafe1ccf7c236

test:
  secret_key_base: 116c78fed61dcce4b4d94931645cd2c0fd50be795f941f493c666814251a382b81dc1003e8165b50f6eaf29d7ddc9d68e2d0967c56d585c7457c1398422ee75c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
